"""Add created_at column to users table

Revision ID: b2445db50837
Revises: 9ce093899489
Create Date: 2025-12-13 00:24:44.360542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2445db50837'
down_revision = '9ce093899489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('token'))

    op.drop_table('invitations')
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.alter_column('joined_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('unique_project_user'))
        batch_op.drop_constraint(batch_op.f('project_members_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('project_members_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('project_members_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.drop_column('invited_by')
        batch_op.drop_column('invitation_token')
        batch_op.drop_column('invitation_sent_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=45),
               nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitation_sent_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('invitation_token', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('invited_by', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('project_members_ibfk_2'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('project_members_ibfk_1'), 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('project_members_ibfk_3'), 'users', ['invited_by'], ['id'])
        batch_op.create_index(batch_op.f('unique_project_user'), ['project_id', 'user_id'], unique=True)
        batch_op.alter_column('joined_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)

    op.create_table('invitations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('invited_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('sent_at', mysql.DATETIME(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('invitations_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('token'), ['token'], unique=True)

    # ### end Alembic commands ###
